name:                ch6
version:             0.1.0.0
github:              "albertodvp/ch6"
license:             BSD3
author:              "Alberto Fanton"
maintainer:          "alberto.fanton@protonmail.com"
copyright:           "Copyright (c) 2022 Alberto Fanton"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Learning

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/albertodvp/ch6#readme>

dependencies:
- base >= 4.7 && < 5
- transformers
- mtl
- filepath
- directory
- unix-compat
- optparse-applicative
- text
- text-show
- unix
- extra
- hspec
- hspec-contrib
- attoparsec
- scientific
ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
default-extensions:
- OverloadedStrings
- RecordWildCards
- NamedFieldPuns

library:
  source-dirs: src
  exposed-modules:
  - Du.AppTypes
  - Du.FileCounter
  - Du.AppRWST
  - Du.DirTree
  - Du.DiskUsage
  - Expr
executables:
  ch6-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ch6
  du:
    main:                Main.hs
    source-dirs:         app/du
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ch6

tests:
  ch6-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ch6
